### ISSUE TITLE
ZTL: QAQC Enhancement

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/data-engineering-qaqc#3]
- [ ] NYCPlanning/db-zoningtaxlots/issues/77
- [ ] NYCPlanning/db-zoningtaxlots/issues/76
- [ ] NYCPlanning/db-zoningtaxlots/issues/75
- [ ] NYCPlanning/db-zoningtaxlots/issues/74
- [ ] NYCPlanning/db-zoningtaxlots/issues/73
- [ ] NYCPlanning/db-zoningtaxlots/issues/72
- [ ] NYCPlanning/db-zoningtaxlots/issues/71
- [ ] NYCPlanning/db-zoningtaxlots/issues/70
- [ ] NYCPlanning/db-zoningtaxlots/issues/69
